# Custom values for prometheus-operator.
# This is a YAML-formatted file. 
# Declare variables to be passed into your templates.

## Configuration for grafana
## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:
   ## Admin credentials
   ##
   adminUser: foo
   adminPassword: bar
   
   ## Configuration for Grafana service
   ##
   service:
      annotations: {}
      labels: {}

      ## Port for Grafana service to listen on
      port: 80

      ## Port to expose on each node
      ## Only used if service.type is 'NodePort'
      type: NodePort
      nodePort: 30080

## Configuration for prometheus
##
prometheus:
   ## Configuration for additional Prometheus service monitors
   ##   
   prometheusSpec:
    additionalServiceMonitors:
      - name: traefik
        additionalLabels:
          - app: traefik
            release: prometheus-operator
        endpoints:
          - port: app
            interval: 5s
        namespaceSelector:
          matchNames:
            - kube-system
        selector:
          matchLabels:
            app: traefik

## Configuration for alertmanager      
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
    ## Deploy alertmanager.
    ##
    enabled: false
