apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1g
  labels:
    type: local
spec:
  storageClassName: local-immediate
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
