apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  selector:
    app: prometheus-grafana
  type: NodePort
  ports:
  - name: prometheus-grafana
    protocol: TCP
    port: 8080
    targetPort: 9090
    nodePort: 30000
