kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
  selector:
     app: traefik
  ports:
    - name: app
      port: 80
      targetPort: 80
    - name: dashboard
      port: 8080
      targetPort: 8080
  type: ClusterIP
