kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: traefik
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: app-services
    - protocol: TCP
      port: 8080
      name: dashboard
    - protocol: TCP
      port: 8008
      name: metrics
  type: NodePort
