apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: traefik
    release: prometheus
  name: traefik
spec:
  endpoints:
  - port: app-services
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: traefik
